# Generated by Django 4.2.7 on 2023-12-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblisting', '0004_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('others', 'others')], default='male', max_length=200),
        ),
    ]
