# Generated by Django 4.2.7 on 2023-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblisting', '0007_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='saved_job',
            field=models.ManyToManyField(null=True, related_name='saved', to='joblisting.jobs'),
        ),
    ]
