# Generated by Django 4.2.7 on 2023-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblisting', '0008_studentprofile_saved_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('part-time', 'part-time'), ('full-time', 'full-time')], default='full-time', max_length=200),
        ),
    ]
