# Generated by Django 4.2.7 on 2023-12-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblisting', '0009_jobs_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default='full-time', max_length=200),
        ),
    ]
